### PR TITLE
Add support to start two machines

### PR DESCRIPTION
**Pull request by surajssd**
* Remove flatcar configs so that only two machines (Ubuntu for AppArmor and Fedora for SELinux) can be supported instead of three.

* This PR provisions two machines instead of one, which was selected via the distro variable.
    
* Remove the distro variable

### CODE REVIEW

**Comment by pothos** [comment]
Can we make it optional? I have the feeling that a lot of time two instead of one instance will be created but still only one will be used.

**Comment by pothos** [comment]
Otherwise it works well (with the `,Z` caddy change).

**Comment by surajssd** [comment]
There was no literal way to figure out how can we have selinux and apparmor at the same time, hence we reached to this decision.

**Comment by surajssd** [comment]
I will wait for one more +1 on this from @alban or @indradhanush

**Comment by indradhanush** [comment]
I am of the opinion that we should *not* start two machines by default. But I was also not able to find a solution to optionally start only one without complicating this further. Given the current state, these changes look okay to me as a result.

**Pull request merged**
